<?xml version="1.0" encoding="utf-8"?><rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom"><channel><atom:link href="http://www.evoolution.ca/RSSRetrieve.aspx?ID=18298&amp;Type=RSS20" rel="self" type="application/rss+xml" /><title>Evoolution</title><description>Evoolution</description><link>http://www.evoolution.ca/</link><lastBuildDate>Fri, 17 Feb 2017 00:13:01 GMT</lastBuildDate><docs>http://backend.userland.com/rss</docs><generator>RSS.NET: http://www.rssdotnet.com/</generator><item><title>Recipe Roundup: Tomatoes</title><description>&lt;p&gt;It&amp;rsquo;s our favourite time of year &amp;ndash; tomato season! Like clockwork, we have been picking up a bunch or two every week, intended for sauce, sandwiches and salads. We say &lt;em&gt;intended,&lt;/em&gt; because, well, &lt;a href="http://www.evoolution.ca/_blog/Evoolution/post/getting-our-fill/"&gt;you know how we feel about tomatoes&lt;/a&gt;. &lt;br /&gt;
&lt;br /&gt;
To keep from eating the whole lot sliced and simply dressed with olive oil and salt (not that there&amp;rsquo;s anything wrong with that), we combed our favourite websites and blogs for some tomato inspiration. It turns out that exercising a little restraint results in a gleaming, ruby-red treasure trove of recipe ideas &amp;ndash; the best use for delayed gratification we&amp;rsquo;ve found yet.&amp;nbsp;  &lt;/p&gt;
&lt;div style="text-align: center;"&gt;&lt;img alt="" style="border: 0px none;" src="/blog images/tomato-grid.png" /&gt; &lt;/div&gt;
&lt;br /&gt;
A tomato sandwich is ideal late-summer fare, and these recipes have convinced us that you &lt;em&gt;can&lt;/em&gt; improve on perfection. Clockwise, from top left:&lt;br /&gt;
&lt;br /&gt;
1. &lt;a href="https://food52.com/recipes/30425-roasted-tomatoes-and-onions-on-toast"&gt;Roasted Tomatoes and Onions on Toast&lt;/a&gt; &amp;nbsp; &lt;br /&gt;
2. &lt;a href="https://food52.com/blog/7873-summer-tomato-tartines-with-garlic-confit "&gt;Summer Tomato Tartines with Garlic Confit&lt;/a&gt; &lt;br /&gt;
3. &lt;a href="https://food52.com/recipes/12088-tomato-sandwich-with-anchovy-aioli"&gt;Tomato Sandwich with Anchovy Aioli&lt;/a&gt;&amp;nbsp; &lt;br /&gt;
4. &lt;a href="http://www.lepainquotidien.com/recipe/pan-con-tomate-recipe/"&gt;Pan con tomate&lt;/a&gt;&lt;br /&gt;
&amp;nbsp;
&lt;p style="text-align: center;"&gt;&lt;span&gt;&lt;img alt="" style="border: 0px none;" src="/blog images/tomato-grid2.png" /&gt;&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;Jams
and sauces are a little more involved, but if you&amp;rsquo;re into canning, they
have the added bonus of keeping you company through the winter.
Clockwise, from top left:&lt;/p&gt;
1. &lt;a href="http://www.emikodavies.com/blog/italian-table-talk-sweet-tomato-jam/ "&gt;Sweet Tomato Jam&lt;/a&gt; &lt;br /&gt;
2. &lt;a href="http://orangette.blogspot.ca/2007/09/start-with-tomato-sauce.html"&gt;Tomato Sauce with Onion and Butter&lt;/a&gt;&amp;nbsp; &lt;br /&gt;
3. &lt;a href="https://food52.com/recipes/23676-roasted-tomato-jam"&gt;Roasted Tomato Jam&lt;/a&gt;&amp;nbsp; &lt;br /&gt;
4. &lt;a href="http://www.thewednesdaychef.com/the_wednesday_chef/2010/10/marcella-hazans-tomato-anchovy-sauce.html "&gt;Tomato Anchovy Sauce &lt;/a&gt;&lt;br /&gt;
&lt;br /&gt;
&lt;p&gt;Happy tomato season! (We&amp;rsquo;re thinking of printing out cards next year.) &lt;/p&gt;
</description><link>http://www.evoolution.ca/RSSRetrieve.aspx?ID=18298&amp;A=Link&amp;ObjectID=1327700&amp;ObjectType=56&amp;O=http%253a%252f%252fwww.evoolution.ca%252f_blog%252fEvoolution%252fpost%252ftomatoes%252f</link><guid isPermaLink="true">http://www.evoolution.ca/_blog/Evoolution/post/tomatoes/</guid><pubDate>Wed, 20 Aug 2014 01:14:00 GMT</pubDate></item><item><title>Iron Chef: Evoolution Edition - Round Six</title><description>&lt;p&gt;&lt;em&gt;&lt;span style="font-size: 14px;"&gt;This is the sixth part in a series. If you've missed them, click for parts &lt;a href="http://www.evoolution.ca/_blog/Evoolution/post/Iron_Chef/"&gt;&lt;span style="color: #1f56b8;"&gt;1&lt;/span&gt;&lt;/a&gt;, &lt;a href="http://www.evoolution.ca/_blog/Evoolution/post/iron-chef-evoolution-edition---round-two/"&gt;&lt;span style="color: #1f56b8;"&gt;2&lt;/span&gt;&lt;/a&gt;, &lt;a href="http://www.evoolution.ca/_blog/Evoolution/post/iron-chef-evoolution-edition---round-three/"&gt;&lt;span style="color: #1f56b8;"&gt;3&lt;/span&gt;&lt;/a&gt;, &lt;a href="http://www.evoolution.ca/_blog/Evoolution/post/iron-chef-evoolution-edition---round-four/"&gt;&lt;span style="color: #1f56b8;"&gt;4&lt;/span&gt;&lt;/a&gt; and &lt;a href="http://www.evoolution.ca/_blog/Evoolution/post/iron-chef-evoolution-edition---round-five/"&gt;&lt;span style="color: #1f56b8;"&gt;5&lt;/span&gt;&lt;/a&gt;.&amp;nbsp;&lt;/span&gt;&lt;/em&gt;&lt;/p&gt;
&lt;p style="text-align: center;"&gt;&lt;img alt="" src="/blog images/group-shot-30-minute.jpg" style="border: 0px;" /&gt;&lt;/p&gt;
&lt;p&gt;Our last staff meeting was the largest one yet, with us having two new stores under our belt this summer! Colin, as winner of the last round, was the judge, and the theme was &amp;ldquo;30 Minute Dishes&amp;rdquo;. It was an impressive showing all around, proving that great food doesn&amp;rsquo;t have to take all day to prepare!&lt;/p&gt;
&lt;p style="text-align: center;"&gt;&lt;img alt="" src="/blog images/pork-fajita.jpg" style="border: 0px;" /&gt;&lt;/p&gt;
&lt;p&gt; &lt;/p&gt;
&lt;p&gt; &lt;/p&gt;
&lt;p style="text-align: center;"&gt;Daniel made a &lt;a href="http://www.evoolution.ca/oils_/ruby-red-grapefruit"&gt;Ruby Red Grapefruit&lt;/a&gt; pork fajita with cherry tomato, bell pepper and avocado, and a cinnamon, &lt;a href="http://www.evoolution.ca/vinegars_/oregano-white-balsamic-vinegar"&gt;Oregano&lt;/a&gt; and goat&amp;rsquo;s cheese dressing&lt;/p&gt;
&lt;p style="text-align: center;"&gt;&lt;img alt="" src="/blog images/baklouti-chicken.jpg" style="border: 0px;" /&gt;&lt;/p&gt;
&lt;p&gt; &lt;/p&gt;
&lt;p&gt; &lt;/p&gt;
&lt;p style="text-align: center;"&gt;Darren made&amp;nbsp;&lt;a href="http://www.evoolution.ca/oils_/baklouti-green-chili-oil"&gt;&lt;span style="color: #2247a2; text-decoration: none;"&gt;Baklouti&lt;/span&gt;&lt;/a&gt;-roasted chicken with a&amp;nbsp;&lt;a href="http://www.evoolution.ca/vinegars_/cara-cara-orange-vanilla"&gt;&lt;span style="color: #2247a2; text-decoration: none;"&gt;Cara Cara Orange Vanilla&lt;/span&gt;&lt;/a&gt;&amp;nbsp;glaze,&amp;nbsp;&lt;a href="http://www.evoolution.ca/oils_/baklouti-green-chili-oil"&gt;&lt;span style="color: #2247a2; text-decoration: none;"&gt;Baklouti&lt;/span&gt;&lt;/a&gt;-roasted root vegetables and peppers, and couscous with&amp;nbsp;&lt;a href="http://www.evoolution.ca/oils_/baklouti-green-chili-oil"&gt;&lt;span style="color: #2247a2; text-decoration: none;"&gt;Baklouti&lt;/span&gt;&lt;/a&gt;&amp;nbsp;and lime&lt;/p&gt;
&lt;p style="text-align: center;"&gt;&lt;img alt="" src="/blog images/greek-pasta-salad.jpg" /&gt;&lt;/p&gt;
&lt;p style="text-align: center;"&gt;Rachel W made a Greek chicken pasta salad with &lt;a href="http://www.evoolution.ca/vinegars_/25-year-sherry-reserva-vinegar"&gt;Sherry Reserva&lt;/a&gt; and &lt;a href="http://www.evoolution.ca/oils_/wild-rosemary"&gt;Rosemary&lt;/a&gt;&lt;/p&gt;
&lt;p&gt; &lt;/p&gt;
&lt;p&gt; &lt;/p&gt;
&lt;p style="text-align: center;"&gt;&lt;img alt="" src="/blog images/pork-and-cabbage.jpg" style="border: 0px;" /&gt;&lt;/p&gt;
&lt;p style="text-align: center;"&gt;Rebekka made a &lt;a href="http://www.evoolution.ca/vinegars_/black-cherry"&gt;Black Cherry&lt;/a&gt;-ginger glazed pork chop with &lt;a href="http://www.evoolution.ca/oils_/harrisa-olive-oil"&gt;Harissa&lt;/a&gt; cabbage&lt;/p&gt;
&lt;p style="text-align: center;"&gt;&lt;img alt="" src="/blog images/chipotle-cheese-dip.jpg" style="border: 0px;" /&gt;&lt;/p&gt;
&lt;p&gt; &lt;/p&gt;
&lt;p&gt; &lt;/p&gt;
&lt;p style="text-align: center;"&gt;Curtis made a &lt;a href="http://www.evoolution.ca/oils_/chipotle-olive-oil"&gt;Chipotle&lt;/a&gt;-&lt;a href="http://www.evoolution.ca/vinegars_/champagne-vinegar"&gt;Champagne&lt;/a&gt; cheese dip with sesame Melba toast and parsley&lt;/p&gt;
&lt;p style="text-align: center;"&gt;&lt;img alt="" src="/blog images/curry-risotto.jpg" style="border: 0px;" /&gt;&lt;/p&gt;
&lt;p&gt; &lt;/p&gt;
&lt;p&gt; &lt;/p&gt;
&lt;p style="text-align: center;"&gt;Rodney made a curried risotto with &lt;a href="http://www.evoolution.ca/vinegars_/lavender-balsamic-vinegar"&gt;Lavender&lt;/a&gt; and Roasted Sesame chicken&lt;/p&gt;
&lt;p style="text-align: center;"&gt;&lt;img alt="" src="/blog images/seafood-curry.jpg" style="border: 0px;" /&gt;&lt;/p&gt;
&lt;p&gt; &lt;/p&gt;
&lt;p&gt; &lt;/p&gt;
&lt;p style="text-align: center;"&gt;EJ made a &lt;a href="http://www.evoolution.ca/oils_/basil-olive-oil"&gt;Basil&lt;/a&gt;-&lt;a href="http://www.evoolution.ca/vinegars_/honey-ginger-white-balsamic-vinegar"&gt;Honey Ginger&lt;/a&gt; green curry with shrimp, scallops and a scallion-basil steamed bun&lt;/p&gt;
&lt;p style="text-align: center;"&gt;&lt;span style="font-size: medium; font-style: normal; font-variant: normal; line-height: 24px; font-family: arial, helvetica, sans-serif;"&gt;&lt;img alt="" src="/blog images/watermelon-feta-salad.jpg" style="border: 0px;" /&gt;&lt;br /&gt;
&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;Rachel P made a &lt;a href="http://www.evoolution.ca/oils_/blood-orange-olive-oil"&gt;&lt;span style="color: #1f56b8;"&gt;Blood Orange&lt;/span&gt;&lt;/a&gt; watermelon-feta salad with &lt;a href="http://www.evoolution.ca/vinegars_/blackberry-ginger-balsamic-vinegar"&gt;&lt;span style="color: #1f56b8;"&gt;Blackberry Ginger&lt;/span&gt;&lt;/a&gt; glazed onions, arugula and mint&amp;nbsp;&lt;/p&gt;
&lt;p style="text-align: center;"&gt;&lt;img alt="" src="/blog images/Walnut-espresso-brownie.jpg" style="border: 0px;" /&gt;&lt;/p&gt;
&lt;p style="text-align: center;"&gt;Azkaa made a &lt;a href="http://www.evoolution.ca/oils_/roasted-french-walnut-oil"&gt;Roasted Walnut&lt;/a&gt; and &lt;a href="http://www.evoolution.ca/vinegars_/espresso-balsamic-vinegar"&gt;Espresso&lt;/a&gt; brownie&lt;/p&gt;
&lt;p style="text-align: left;"&gt;Everyone ooh-ed and aah-ed at each other's efforts while Colin deliberated, and Azkaa's sweet treat won out! Congratulations to Azkaa, and thank you for joining us for another round of Iron Chef: Evoolution Edition!&amp;nbsp;&lt;/p&gt;
</description><link>http://www.evoolution.ca/RSSRetrieve.aspx?ID=18298&amp;A=Link&amp;ObjectID=1313637&amp;ObjectType=56&amp;O=http%253a%252f%252fwww.evoolution.ca%252f_blog%252fEvoolution%252fpost%252firon-chef-evoolution-edition-round-six%252f</link><guid isPermaLink="true">http://www.evoolution.ca/_blog/Evoolution/post/iron-chef-evoolution-edition-round-six/</guid><pubDate>Thu, 24 Jul 2014 21:18:00 GMT</pubDate></item><item><title>Iron Chef: Evoolution Edition - Round Five</title><description>&lt;p style="text-align: center;"&gt;&lt;img alt="" src="/blog images/gluten-free-desserts.jpg" style="border: 0px;" /&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style="font-family: georgia; color: #1a1a1a;"&gt;We had the latest instalment of Iron Chef: Evoolution a little while ago, and it was the sweetest one yet! The theme was "Gluten-Free Desserts", and everybody rose to the challenge admirably.&lt;/span&gt;&lt;/p&gt;
&lt;p&gt; &lt;/p&gt;
&lt;p&gt; &lt;/p&gt;
&lt;p&gt; &lt;/p&gt;
&lt;p style="text-align: center;"&gt;&lt;span style="font-family: georgia; color: #1a1a1a;"&gt;&lt;img alt="" src="/blog images/blackberry-ginger-scone.jpg" style="border: 0px;" /&gt;&lt;br /&gt;
&lt;/span&gt;&lt;/p&gt;
&lt;p style="text-align: center;"&gt;&lt;span style="font-family: georgia; color: #1a1a1a;"&gt;Darren made ginger scones with&lt;a href="http://www.evoolution.ca/vinegars_/blackberry-ginger-balsamic-vinegar"&gt; Blackberry-Ginger&lt;/a&gt; mole reduction&lt;/span&gt;&lt;/p&gt;
&lt;p style="text-align: center;"&gt;&lt;span style="font-family: georgia; color: #1a1a1a;"&gt;&lt;img alt="" src="/blog images/cinnamon-bun-gf.jpg" style="border: 0px;" /&gt;&lt;br /&gt;
&lt;/span&gt;&lt;/p&gt;
&lt;p&gt; &lt;/p&gt;
&lt;p style="text-align: center;"&gt;&lt;span style="font-family: georgia; color: #1a1a1a;"&gt;Colin made cinnamon buns with &lt;a href="http://www.evoolution.ca/vinegars_/red-apple-balsamic-vinegar"&gt;Red Apple&lt;/a&gt;-maple syrup reduction&lt;/span&gt;&lt;/p&gt;
&lt;p style="text-align: center;"&gt;&lt;span style="font-family: georgia; color: #1a1a1a;"&gt;&lt;img alt="" src="/blog images/coconut-cassava-cake.jpg" style="border: 0px;" /&gt;&lt;br /&gt;
&lt;/span&gt;&lt;/p&gt;
&lt;p&gt; &lt;/p&gt;
&lt;p style="text-align: center;"&gt;&lt;span style="font-family: georgia; color: #1a1a1a;"&gt;EJ made &lt;a href="http://www.evoolution.ca/vinegars_/alfoos-mango-white-balsamic-vinegar"&gt;Alfoos Mango&lt;/a&gt;-coconut cassava cake with coconut custard&lt;/span&gt;&lt;/p&gt;
&lt;p style="text-align: center;"&gt;&lt;span style="font-family: georgia; color: #1a1a1a;"&gt;&lt;img alt="" src="/blog images/lemon-almond-muffin.jpg" style="border: 0px;" /&gt;&lt;br /&gt;
&lt;/span&gt;&lt;/p&gt;
&lt;p&gt; &lt;/p&gt;
&lt;p style="text-align: center;"&gt;&lt;span style="font-family: georgia; color: #1a1a1a;"&gt;Azkaa made &lt;a href="http://www.evoolution.ca/oils_/eureka-lemon-olive-oil"&gt;Eureka Lemon&lt;/a&gt; almond muffins with lavender glaze and local florae (and home-ground flour!)&lt;/span&gt;&lt;/p&gt;
&lt;p style="text-align: center;"&gt;&lt;span style="font-family: georgia; color: #1a1a1a;"&gt;&lt;img alt="" src="/blog images/blood-orange-truffle.jpg" style="border: 0px;" /&gt;&lt;br /&gt;
&lt;/span&gt;&lt;/p&gt;
&lt;p&gt; &lt;/p&gt;
&lt;p style="text-align: center;"&gt;&lt;span style="font-family: georgia; color: #1a1a1a;"&gt;Curtis made &lt;a href="http://www.evoolution.ca/oils_/blood-orange-olive-oil"&gt;Blood Orange&lt;/a&gt; chocolate truffles&lt;/span&gt;&lt;/p&gt;
&lt;p&gt; &lt;/p&gt;
&lt;p&gt; &lt;/p&gt;
&lt;p&gt; &lt;/p&gt;
&lt;p style="text-align: left;"&gt;&lt;span style="font-family: georgia;"&gt;&lt;span style="color: #1a1a1a;"&gt;&lt;span style="font-family: georgia;"&gt;This was the first challenge in which Rachel W, our judge and resident gluten-free'er, was able to taste all of the dishes. Everyone commenced getting a sugar high while she deliberated. Colin was crowned the winner, to much applause! He'll judge the next challenge in June...stay tuned for &lt;/span&gt;&lt;span style="font-size: 16px;"&gt;&lt;span style="font-size: 16px; font-family: georgia;"&gt;"30 Minut&lt;/span&gt;&lt;span style="font-size: 16px;"&gt;e&lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;span style="font-size: 16px; color: #1a1a1a;"&gt; Meals"!&amp;nbsp;&lt;/span&gt;&lt;/span&gt;&lt;/p&gt;
</description><link>http://www.evoolution.ca/RSSRetrieve.aspx?ID=18298&amp;A=Link&amp;ObjectID=1294863&amp;ObjectType=56&amp;O=http%253a%252f%252fwww.evoolution.ca%252f_blog%252fEvoolution%252fpost%252firon-chef-evoolution-edition---round-five%252f</link><guid isPermaLink="true">http://www.evoolution.ca/_blog/Evoolution/post/iron-chef-evoolution-edition---round-five/</guid><pubDate>Sat, 31 May 2014 16:11:00 GMT</pubDate></item><item><title>For Your Valentine</title><description>&lt;p&gt;&lt;span style="font-family: georgia;"&gt;Cooking for that special someone this weekend? &lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style="font-family: georgia;"&gt;Here are some menu ideas to ensure you have the perfect evening: &lt;/span&gt;&lt;/p&gt;
&lt;p style="text-align: center;"&gt;&lt;span style="font-family: georgia;"&gt;&lt;img alt="" src="/images/Recipes/pan-seared-scallops-tomato-salsa-lg1.png" style="border: 0px;" /&gt;&lt;br /&gt;
&lt;/span&gt;&lt;/p&gt;
&lt;p style="text-align: center;"&gt;&lt;span style="font-family: georgia;"&gt;&lt;a href="http://www.evoolution.ca/recipes/pan-seared-scallops-with-warm-tomato-salsa"&gt;Pan-Seared Scallops with Warm Tomato Salsa&lt;/a&gt;&lt;/span&gt;&lt;/p&gt;
&lt;p style="text-align: center;"&gt;&lt;img alt="" src="/images/Recipes/caprese-bruschetta.jpg" style="border: 0px;" /&gt;&lt;/p&gt;
&lt;p style="text-align: center;"&gt;&lt;a href="http://www.evoolution.ca/recipes/caprese-bruschetta" style="font-family: georgia; font-size: inherit; text-align: left;"&gt;Caprese Bruschetta&lt;/a&gt;&lt;/p&gt;
&lt;p style="text-align: center;"&gt;&lt;img alt="" src="/images/Recipes/fennel-radicchio-endive.jpg" style="border: 0px;" /&gt;&lt;/p&gt;
&lt;p style="text-align: center;"&gt;&lt;span style="font-family: georgia;"&gt;&lt;a href="http://www.evoolution.ca/recipes/fennel-endive-and-radicchio-salad"&gt;Fennel, Endive and Radicchio Salad with Orange Vinaigrette&lt;/a&gt;&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;
&lt;div style="text-align: center;"&gt;&lt;img alt="" src="/images/Recipes/juniperlamb.jpg" style="font-family: georgia;" /&gt;&lt;/div&gt;
&lt;span style="font-family: georgia;"&gt;
&lt;div style="text-align: center;"&gt;&lt;br /&gt;
&lt;/div&gt;
&lt;div style="text-align: center;"&gt;&lt;a href="http://www.evoolution.ca/recipes/juniper-berry-rack-of-lamb"&gt;&lt;/a&gt;&lt;a href="http://www.evoolution.ca/recipes/juniper-berry-rack-of-lamb" style="font-family: georgia; font-size: inherit;"&gt;Juniper Berry Rack of Lamb&lt;/a&gt;&lt;br /&gt;
&lt;/div&gt;
&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;
&lt;div style="text-align: center;"&gt;&lt;img alt="" src="/images/Recipes/filetofsole.jpg" style="font-family: georgia;" /&gt;&lt;/div&gt;
&lt;span style="font-family: georgia;"&gt;
&lt;div style="text-align: center;"&gt;&lt;br /&gt;
&lt;/div&gt;
&lt;div style="text-align: center;"&gt;&lt;a href="http://www.evoolution.ca/recipes/filet-of-sole-with-tomatoes-and-olives"&gt;&lt;/a&gt;&lt;a href="http://www.evoolution.ca/recipes/filet-of-sole-with-tomatoes-and-olives" style="font-family: georgia; font-size: inherit;"&gt;Pan-Fried Sole with Tomatoes and Olives&lt;/a&gt;&lt;br /&gt;
&lt;/div&gt;
&lt;/span&gt;&lt;/p&gt;
&lt;p style="text-align: center;"&gt;&lt;span style="font-family: georgia;"&gt;&lt;img alt="" src="/images/Recipes/blood-orange-chocolate-mousse-lg1.png" style="border: 0px;" /&gt;&lt;br /&gt;
&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;
&lt;div style="text-align: center;"&gt;&lt;a href="http://www.evoolution.ca/recipes/blood-orange-chocolate-mousse" style="font-family: georgia; font-size: inherit;"&gt;Blood Orange Chocolate Mousse&lt;/a&gt;&lt;/div&gt;
&lt;span style="font-family: georgia;"&gt;
&lt;div style="text-align: center;"&gt;&lt;br /&gt;
&lt;/div&gt;
&lt;div style="text-align: center;"&gt;&lt;img alt="" src="/images/Recipes/Chipotle-Brownies-Dark-Chocolate-Caramel-lg.png" style="font-family: georgia;" /&gt;&lt;/div&gt;
&lt;div style="text-align: center;"&gt;&lt;br /&gt;
&lt;/div&gt;
&lt;div style="text-align: center;"&gt;&lt;a href="http://www.evoolution.ca/recipes/chipotle-brownies-with-dark-chocolate-caramel-sauce"&gt;&lt;/a&gt;&lt;a href="http://www.evoolution.ca/recipes/chipotle-brownies-with-dark-chocolate-caramel-sauce" style="font-family: georgia; font-size: inherit;"&gt;Chipotle Brownies with Dark Chocolate Caramel Sauce&lt;/a&gt;&lt;br /&gt;
&lt;/div&gt;
&lt;/span&gt;&lt;/p&gt;
&lt;span style="font-size: 12pt;"&gt;&lt;span style="font-family: georgia;"&gt;And don&amp;rsquo;t forget to pick up some of The Violet Chocolate Co. &amp;lsquo;s popular bars! The hot chocolate is also flying off the shelves&amp;hellip;&lt;/span&gt;&lt;br /&gt;
&lt;br /&gt;
&lt;div style="text-align: center;"&gt;&lt;img alt="" src="/blog images/violet-choc.jpg" /&gt;&lt;/div&gt;
&lt;/span&gt;
</description><link>http://www.evoolution.ca/RSSRetrieve.aspx?ID=18298&amp;A=Link&amp;ObjectID=1214346&amp;ObjectType=56&amp;O=http%253a%252f%252fwww.evoolution.ca%252f_blog%252fEvoolution%252fpost%252ffor-your-valentine%252f</link><guid isPermaLink="true">http://www.evoolution.ca/_blog/Evoolution/post/for-your-valentine/</guid><pubDate>Mon, 10 Feb 2014 18:33:00 GMT</pubDate></item><item><title>Oil in the Ancient World: Ancient Egypt</title><description>&lt;p&gt;The Ancient Egyptians, like all ancient peoples, greatly valued oil; but unlike their neighbours to the East and West, they did not profit from large-scale production of olive oil until around 330 BCE. It has been posited that the climate in Egypt at the time was not ideal for growing olive trees. More likely, though, is the idea that the trading of domestic goods for olive oil benefited the Egyptian elite; limited quantities ensured that the product became a true luxury, thereby elevating the status of those who could secure it. This powerful commodity was integral to the increased class distinction in the emerging state, and Palestine, Mesopotamia and the Mediterranean were all too eager to trade with Egypt to cement their ties. &lt;/p&gt;
&lt;p style="text-align: center;"&gt;&lt;img alt="" src="/blog images/Egypt-_Egypt-landscape_6722.jpg" style="border: 0px;" /&gt;&lt;/p&gt;
&lt;p&gt; &lt;/p&gt;
&lt;p&gt; &lt;/p&gt;
&lt;p style="text-align: center;"&gt;&lt;span style="font-size: 10px;"&gt;Image found &lt;a href="http://www.bestourism.com/img/items/big/100/Egypt-_Egypt-landscape_6722.jpg"&gt;here&lt;/a&gt;&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;Egypt was also famous throughout the ancient world for its essential oils and perfumes. Olive oil was considered an ideal carrier, but widespread oils like castor, linseed and safflower were used more commonly. Unlike in Ancient Greece and Rome, olive oil was not used in large quantities, such as for fuel, but rather saved for cosmetic purposes and food, for those who could afford it. &lt;/p&gt;
&lt;p style="text-align: center;"&gt;&lt;img alt="" src="/blog images/ancient-egypt-papyrus.jpg" style="border: 0px;" /&gt;&lt;/p&gt;
&lt;p&gt; &lt;/p&gt;
&lt;p&gt; &lt;/p&gt;
&lt;p style="text-align: center;"&gt;&lt;span style="font-size: 10px;"&gt;Image found &lt;a href="http://www.sheknows.com/beauty-and-style/articles/813279/at-home-beauty-treatment-inspired-by-ancient-egypt"&gt;here&lt;/a&gt;&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;Under Greek (and later, Roman) rule, olive cultivation dramatically increased in Egypt. As olive oil became available to a larger percentage of people, the Egyptians eventually came to adopt many of the ritual and everyday practices of the rest of the Greco-Roman world; in particular, they began offering olive oil to the gods, placing jugs of olive oil in the tombs of the deceased, and using it as a medicinal ingredient.&amp;nbsp;&lt;/p&gt;
</description><link>http://www.evoolution.ca/RSSRetrieve.aspx?ID=18298&amp;A=Link&amp;ObjectID=1211419&amp;ObjectType=56&amp;O=http%253a%252f%252fwww.evoolution.ca%252f_blog%252fEvoolution%252fpost%252foil-in-the-ancient-world-ancient-egypt%252f</link><guid isPermaLink="true">http://www.evoolution.ca/_blog/Evoolution/post/oil-in-the-ancient-world-ancient-egypt/</guid><pubDate>Thu, 06 Feb 2014 05:00:00 GMT</pubDate></item><item><title>Oil in the Ancient World: Ancient Rome</title><description>&lt;div style="text-align: center;"&gt;
&lt;div style="text-align: left;"&gt;
&lt;p style="margin-bottom: 24pt;"&gt;Although it made its way into the myths of the time -- the goddess Minerva is credited with creating the olive tree in Roman mythology, much like Athena in Greek mythology, and legend also states that brothers Romulus and Remus, the demi-gods that founded Rome, were born under an olive tree --&amp;nbsp;the olive tree in Ancient Rome was not initially as sanctified as it was in Ancient Greece. This changed rapidly, however, as the Greek Empire spread olive cultivation to its colonies.&amp;nbsp;&lt;/p&gt;
&lt;/div&gt;
&lt;/div&gt;
&lt;div style="text-align: center;"&gt;&lt;img alt="" src="/blog images/olivepress.jpg" style="font-family: arial, helvetica, sans-serif; font-size: medium; font-style: normal; font-variant: normal; line-height: 24px; text-align: center;" /&gt;&lt;/div&gt;
&lt;div style="text-align: center;"&gt;&lt;span style="font-size: 10px;"&gt;&lt;span style="font-size: 10px;"&gt;&lt;/span&gt;Image found &lt;a href="http://oxrep.classics.ox.ac.uk/index.php?pg=33"&gt;here&lt;/a&gt;&lt;/span&gt;&lt;/div&gt;
&lt;div style="text-align: center;"&gt;&lt;br /&gt;
&lt;/div&gt;
&lt;p style="margin-bottom: 24pt;"&gt;Greek colonists introduced olive cultivation to Southern Italy around the 8&lt;sup&gt;th&lt;/sup&gt;&amp;nbsp;century BCE, but it was the Romans who revolutionized the process and made olive oil a valuable commodity on the international trade market. The Romans were the first to start crushing the olives in roller mills, which separated the pulp without bruising the pits. The resulting liquid was left to sit until it separated, and the high-quality oil was skimmed off the top; the remaining pulp was then pressed again to extract a lower-quality olive oil. After the second pressing, the pulp was put to use as fertilizer.&lt;br /&gt;
&lt;br /&gt;
In the beginning, olive oil was not widely used for food; while whole olives were eaten during meals, olive oil was generally reserved for cosmetic and medical applications. Rancid oil, in particular, was used for lighting due to its lower water content.&amp;nbsp; Of course, the famous Roman baths made liberal use of olive oil; those who could afford this luxury would have the oil massaged into their body and scraped off with a strigil before bathing.&lt;/p&gt;
&lt;p style="text-align: center;"&gt;&lt;img alt="" src="/blog images/RomanBathhouse2.jpg" style="border: 0px;" /&gt;&lt;/p&gt;
&lt;p style="text-align: center;"&gt;
&lt;/p&gt;
&lt;div style="text-align: center;"&gt;&lt;span style="line-height: 1.5; font-family: arial, helvetica, sans-serif; font-size: 10px;"&gt;Image found &lt;/span&gt;&lt;a href="http://www.crystalinks.com/romebaths.html" style="font-size: 10px; font-family: arial, helvetica, sans-serif;"&gt;here&lt;/a&gt;&lt;/div&gt;
&lt;div style="text-align: center;"&gt;&lt;br /&gt;
&lt;/div&gt;
&lt;p&gt;As the Roman Empire expanded, so did olive oil production in its colonies, especially Spain and North Africa. Rome imposed taxes on these colonies in the form of olive oil, ensuring a steady supply for international trade purposes. Needless to say, thanks to innovative techniques and economic strategies, the Empire profited immensely from this &amp;lsquo;liquid gold&amp;rsquo; until its ultimate decline and fall, of which the oil market was a casualty.&amp;nbsp;&lt;/p&gt;
</description><link>http://www.evoolution.ca/RSSRetrieve.aspx?ID=18298&amp;A=Link&amp;ObjectID=1199568&amp;ObjectType=56&amp;O=http%253a%252f%252fwww.evoolution.ca%252f_blog%252fEvoolution%252fpost%252foil-in-the-ancient-world-ancient-rome%252f</link><guid isPermaLink="true">http://www.evoolution.ca/_blog/Evoolution/post/oil-in-the-ancient-world-ancient-rome/</guid><pubDate>Sat, 25 Jan 2014 21:46:00 GMT</pubDate></item><item><title>Oil in the Ancient World: Ancient Greece</title><description>&lt;p&gt;Here at Evoolution, we regard olive oil as more than just an ingredient in cooking, and we find ourselves using it more and more in our daily routines. Over the next couple of weeks, we&amp;rsquo;ll be drawing inspiration from the ancient world, looking at the practices surrounding oil in many great civilizations.&lt;/p&gt;
&lt;p style="text-align: center;"&gt;&lt;span style="font-style: normal; font-variant: normal; line-height: 15px; font-family: arial, helvetica, sans-serif; font-size: 10px;"&gt;&lt;img alt="" src="/blog images/erechtheion_athens_greece.jpg" style="border: 0px;" /&gt;&lt;br /&gt;
&lt;/span&gt;&lt;/p&gt;
&lt;p style="text-align: center;"&gt;&lt;span style="font-style: normal; font-variant: normal; line-height: 15px; font-family: arial, helvetica, sans-serif; font-size: 10px;"&gt;Image found&amp;nbsp;&lt;/span&gt;&lt;a href="http://www.globeimages.net/img-erechtheion-athens-greece-8870.htm" style="font-family: arial, helvetica, sans-serif; font-size: 10px; font-style: normal; font-variant: normal;"&gt;here&lt;/a&gt;&lt;span style="font-style: normal; font-variant: normal; line-height: 15px; font-family: arial, helvetica, sans-serif; font-size: 10px;"&gt;.&amp;nbsp;&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;Where better to start than Ancient Greece? &lt;/p&gt;
&lt;p&gt;It is said that the city of Athens was so-named because of an olive tree. According to this Ancient Greek mythology, the gods of Olympus set out to rename the city of Cecropia, originally named for its founder, Cecrops. Poseidon, god of the sea, and Athena, goddess of wisdom and courage, found themselves in great dispute, as both wanted to give their name to the city. To end the argument, Zeus decided that each of them would give the city a gift, and the city would decide who would become their patron. Poseidon, for his part, struck a rock with his trident, causing a spring of saltwater to gush forth. Athena planted a seed in the ground, from which grew an olive tree. King Cecrops and his citizens deemed the olive tree the superior gift, and the city was henceforth known as Athens.&lt;/p&gt;
&lt;p&gt;
&lt;/p&gt;
&lt;div style="font-family: arial, helvetica, sans-serif; font-size: medium; font-style: normal; font-variant: normal; line-height: 24px; text-align: center;"&gt;&lt;span style="font-family: arial, helvetica, sans-serif;"&gt;&lt;img alt="" src="/blog images/Olive_trees_on_Thassos.jpg" /&gt;&lt;br /&gt;
&lt;/span&gt;&lt;/div&gt;
&lt;div style="font-family: arial, helvetica, sans-serif; font-size: medium; font-style: normal; font-variant: normal; line-height: 24px; text-align: center;"&gt;&lt;span style="font-family: arial, helvetica, sans-serif;"&gt;&lt;br /&gt;
&lt;/span&gt;&lt;/div&gt;
&lt;div style="font-family: arial, helvetica, sans-serif; font-size: medium; font-style: normal; font-variant: normal; line-height: 24px; text-align: center;"&gt;&lt;span style="font-family: arial, helvetica, sans-serif; font-size: 10px;"&gt;Image found&amp;nbsp;&lt;a href="http://en.wikipedia.org/wiki/File:Olive_trees_on_Thassos.JPG"&gt;here&lt;/a&gt;.&lt;/span&gt;&lt;/div&gt;
&lt;p&gt;This etiological myth is a testament to the significance of the olive tree in Ancient Greece. It is no wonder that the soon-to-be Athenians would find the olive tree to be so pleasing; it produced a number of useful things, from fruit to firewood (olive wood is surprisingly effective fuel for a fire, once it&amp;rsquo;s been started). Chief among these useful products was olive oil, which was immensely versatile; for example:&lt;/p&gt;
&lt;ul&gt;
    &lt;li&gt;&lt;span style="line-height: 1.5; font-family: arial, helvetica, sans-serif;"&gt;Athletes would have olive oil massaged into their skin before physical activity to prevent injuries, and afterward to prevent soreness.&lt;/span&gt;&lt;/li&gt;
    &lt;li&gt;&lt;span style="line-height: 1.5; font-family: arial, helvetica, sans-serif;"&gt;It was used for exfoliation, being spread onto skin with sand or ash and scraped off with a strigil.&lt;/span&gt;&lt;/li&gt;
    &lt;li&gt;&lt;span style="line-height: 1.5; font-family: arial, helvetica, sans-serif;"&gt;In perfumes, olive oil was used as a carrier oil, much like alcohol is used today, being embellished with plant-based ingredients like flowers, leaves and seeds for fragrance.&lt;/span&gt;&lt;/li&gt;
    &lt;li&gt;&lt;span style="line-height: 1.5; font-family: arial, helvetica, sans-serif;"&gt;It was used as fuel for oil lamps&lt;/span&gt;&lt;/li&gt;
    &lt;li&gt;&lt;span style="line-height: 1.5; font-family: arial, helvetica, sans-serif;"&gt;Ulcers, burns and other wounds were treated with olive oil&lt;/span&gt;&lt;/li&gt;
    &lt;li&gt;&lt;span style="line-height: 1.5; font-family: arial, helvetica, sans-serif;"&gt;It was used for anointing newborn babies and the deceased, and was offered to the gods as a sacrifice&lt;/span&gt;&lt;/li&gt;
    &lt;li&gt;&lt;span style="line-height: 1.5; font-family: arial, helvetica, sans-serif;"&gt;Olive oil was so highly valued that it was even given as a prize to the winners at the Panathenaic Games in Athens.&lt;/span&gt;&lt;/li&gt;
&lt;/ul&gt;
&lt;div style="text-align: center;"&gt;&lt;br /&gt;
&lt;/div&gt;
&lt;p&gt;Olive oil was, of course, used liberally in food; its health benefits were widely touted by early physicians such as Hippocrates, who recommended that grains, legumes and vegetables be served &amp;lsquo;well-oiled&amp;rsquo;. For fortification, it was also recommended to eat pieces of hot bread dipped in wine and olive oil; we&amp;rsquo;re not sure if we&amp;rsquo;ll be trying this anytime soon, but it does sound oddly heartening.&amp;nbsp;&lt;/p&gt;
</description><link>http://www.evoolution.ca/RSSRetrieve.aspx?ID=18298&amp;A=Link&amp;ObjectID=1192959&amp;ObjectType=56&amp;O=http%253a%252f%252fwww.evoolution.ca%252f_blog%252fEvoolution%252fpost%252foil-in-the-ancient-world-greece%252f</link><guid isPermaLink="true">http://www.evoolution.ca/_blog/Evoolution/post/oil-in-the-ancient-world-greece/</guid><pubDate>Thu, 16 Jan 2014 05:00:00 GMT</pubDate></item><item><title>Handled with care</title><description>&lt;p&gt;It can be hard to get excited about salad in winter &amp;ndash; gone are the delicate lettuces of summer, the fleshy tomatoes that need nothing more than good olive oil and salt to come alive. The market fills instead with piles of squash, root vegetables and hearty greens, all of which need a bit of coaxing before gracing our plates.&lt;/p&gt;
&lt;p&gt;But there is a certain charm to the humble vegetables of winter, to smoothing out their rough edges and finding out what makes them tick. While it is easy to heap praise upon the glistening turkeys and buttery side dishes of the season, we urge you to save salad from being an afterthought on your table. After our fair share of winters in Edmonton, we can say with all honesty that a winter salad, handled with care, might even beat out a plate of ripe tomatoes and sweet corn in July. &lt;/p&gt;
&lt;p style="text-align: center;"&gt;&lt;img alt="" src="/blog images/winter-salad.jpg" style="border: 0px;" /&gt;&lt;/p&gt;
&lt;p&gt;A good winter salad is complex, both aesthetically and texturally. It is essential in these cold, dark months to fill our plates with colour and crunch, so as to refresh both the eyes and the palate. A cold salad in winter is lovely, and a warm one just as welcome; indeed, a winter salad can be both at the same time &amp;ndash; think roasted squash adorned with cool yogurt and pomegranate. &lt;/p&gt;
&lt;p style="text-align: center;"&gt;&lt;img alt="" src="/images/Recipes/fennel-radicchio-endive.jpg" style="border: 0px;" /&gt;&lt;/p&gt;
&lt;p&gt;The flavour, too, tends to be more sophisticated than that of the simple salads of summer. A winter salad needs to be bold enough to hold its own against the other heavy hitters on the holiday table. We reach for bitter lettuces to contrast the richness of the season, garnishing them with pungent anchovies or olives for bracing bite. Balance, too, is key, so the tart juiciness of citrus, persimmon or pomegranate is desirable. &lt;/p&gt;
&lt;p&gt;Here are a few ideas for wonderful winter salads. We&amp;rsquo;ll be eating a lot of these in the next few weeks, in between bites of leftover cookies.&lt;/p&gt;
&lt;ul&gt;
    &lt;li&gt;shredded raw beets and carrots with parsley, walnuts and &lt;a href="http://www.evoolution.ca/vinegars_/honey-ginger-white-balsamic-vinegar"&gt;Honey Ginger&lt;/a&gt;&amp;nbsp;balsamic&lt;/li&gt;
    &lt;li&gt;shaved fennel and pear with hazelnuts and &lt;a href="http://www.evoolution.ca/vinegars_/cinnamon-pear-balsamic-vinegar"&gt;Cinnamon Pear&lt;/a&gt; balsamic&lt;/li&gt;
    &lt;li&gt;sliced orange and grapefruit with green olives and red onion&lt;/li&gt;
    &lt;li&gt;roasted squash and kale with pomegranate seeds and &lt;a href="http://www.evoolution.ca/vinegars_/25-year-sherry-reserva-vinegar"&gt;Sherry Reserva&lt;/a&gt;&amp;nbsp;vinegar&lt;/li&gt;
    &lt;li&gt;shaved raw Brussels sprouts with pecans, apples and &lt;a href="http://www.evoolution.ca/_blog/Evoolution/post/oil-and-vinegar---emulsified/"&gt;mustard vinaigrette&lt;/a&gt;&lt;/li&gt;
&lt;/ul&gt;
&lt;p&gt;pictured above:&lt;/p&gt;
&lt;ul&gt;
    &lt;li&gt;&lt;a href="http://www.evoolution.ca/recipes/fennel-endive-and-radicchio-salad"&gt;Fennel, Endive and Radicchio Salad&lt;/a&gt; with &lt;a href="http://www.evoolution.ca/recipes/orange-vinaigrette"&gt;Orange Vinaigrette&lt;/a&gt;&lt;/li&gt;
    &lt;li&gt;baby kale with almonds, candied ginger and pomegranate seeds with&amp;nbsp;&lt;a href="http://www.evoolution.ca/oils_/persian-lime-olive-oil"&gt;Persian Lime&lt;/a&gt;&amp;nbsp;oil and &lt;a href="http://www.evoolution.ca/vinegars_/pomegranate-quince"&gt;Pomegranate-Quince&lt;/a&gt;&amp;nbsp;balsamic (made by Azkaa)&lt;/li&gt;
&lt;/ul&gt;
&lt;br /&gt;
</description><link>http://www.evoolution.ca/RSSRetrieve.aspx?ID=18298&amp;A=Link&amp;ObjectID=1177833&amp;ObjectType=56&amp;O=http%253a%252f%252fwww.evoolution.ca%252f_blog%252fEvoolution%252fpost%252fhandled-with-care%252f</link><guid isPermaLink="true">http://www.evoolution.ca/_blog/Evoolution/post/handled-with-care/</guid><pubDate>Sun, 22 Dec 2013 05:00:00 GMT</pubDate></item><item><title>A good party</title><description>&lt;p&gt;&lt;a href="http://www.evoolution.ca/_blog/Evoolution/post/clear-your-plans/"&gt;Like we said&lt;/a&gt;, we do enjoy a good party &amp;ndash; but we still like to keep things simple if we&amp;rsquo;re hosting, if for no other reason than to spend more time with our guests! In our opinion, the most pleasant conversations occur before everyone is called to the table, when guests can unwind and take the edge off their hunger with a few small offerings. So why not make it last all evening? Especially around the holidays, there is something to be said for putting out an array of nibbles and letting everyone help themselves as they please. &lt;/p&gt;
&lt;p&gt; &lt;/p&gt;
&lt;p&gt; &lt;/p&gt;
&lt;p&gt;Here are a few recipes to get you started; it&amp;rsquo;s delicious food, without the fuss (the one exception is dessert; if there was ever something worth fussing over&amp;hellip;):&lt;/p&gt;
&lt;p&gt;
&lt;div style="text-align: center;"&gt;&lt;img alt="" src="/images/Recipes/candied-nuts1.jpg" /&gt;&lt;/div&gt;
&lt;/p&gt;
&lt;p style="text-align: center;"&gt;&lt;a href="http://www.evoolution.ca/recipes/balsamic-candied-nuts"&gt;Balsamic Candied Nuts&lt;/a&gt;&lt;/p&gt;
&lt;p style="text-align: center;"&gt;&lt;img alt="" src="/images/Recipes/popcorn.jpg" style="border: 0px;" /&gt;&lt;/p&gt;
&lt;p style="text-align: center;"&gt;&lt;a href="http://www.evoolution.ca/recipes/truffle-popcorn"&gt;Truffle Popcorn&lt;/a&gt;&lt;/p&gt;
&lt;p style="text-align: center;"&gt;&lt;img alt="" src="/images/Recipes/chipotle-hummus-lg.png" style="border: 0px;" /&gt;&lt;/p&gt;
&lt;p style="text-align: center;"&gt;&lt;a href="http://www.evoolution.ca/recipes/chipotle-hummus"&gt;Chipotle Hummus&lt;/a&gt;&lt;/p&gt;
&lt;p style="text-align: center;"&gt;&lt;img alt="" src="/images/Recipes/caprese-bruschetta.jpg" style="border: 0px;" /&gt;&lt;/p&gt;
&lt;p style="text-align: center;"&gt;&lt;a href="http://www.evoolution.ca/recipes/truffle-popcorn"&gt;Caprese Bruschetta&lt;/a&gt;&lt;/p&gt;
&lt;p style="text-align: center;"&gt;&lt;img alt="" src="/blog images/balsamic-caramelized-onion-tart.jpg" style="border: 0px;" /&gt;&lt;/p&gt;
&lt;p style="text-align: center;"&gt;&lt;a href="http://www.evoolution.ca/recipes/balsamic-caramelized-onion-tart"&gt;Caramelized Onion Tart&lt;/a&gt;&lt;/p&gt;
&lt;p style="text-align: center;"&gt;&lt;img alt="" src="/blog images/sticky-toffee-pudding.jpg" style="border: 0px;" /&gt;&lt;/p&gt;
&lt;p style="text-align: center;"&gt;&lt;a href="http://www.evoolution.ca/recipes/sticky-date-pudding-with-balsamic-toffee-sauce"&gt;Sticky Date Pudding with Balsamic Toffee Sauce&lt;/a&gt;&lt;/p&gt;
</description><link>http://www.evoolution.ca/RSSRetrieve.aspx?ID=18298&amp;A=Link&amp;ObjectID=1170663&amp;ObjectType=56&amp;O=http%253a%252f%252fwww.evoolution.ca%252f_blog%252fEvoolution%252fpost%252fa-good-party%252f</link><guid isPermaLink="true">http://www.evoolution.ca/_blog/Evoolution/post/a-good-party/</guid><pubDate>Fri, 13 Dec 2013 23:32:00 GMT</pubDate></item><item><title>Clear your plans</title><description>&lt;p&gt;&amp;nbsp; &amp;nbsp; &amp;nbsp;There&amp;rsquo;s nothing we like more than a relaxed breakfast or brunch with friends &amp;ndash; especially at this time of year, when fancy, formal parties abound (though we of course enjoy these as well). If you time it well enough, the sun will be rising as you apply the finishing touches to the meal, and you and your guests can gather around the table and usher in the daylight together. &lt;/p&gt;
&lt;p&gt; &lt;/p&gt;
&lt;p&gt; &lt;/p&gt;
&lt;p&gt;&amp;nbsp; &amp;nbsp; &amp;nbsp;We&amp;rsquo;ve compiled a few of our recipes to make a lovely spread for a morning meal - simply add some fresh juice and a balsamic fruit salad. Stop in to the store and pick up a few items for yourself while you&amp;rsquo;re buying your gifts, tell some friends to come &amp;lsquo;round and then clear your plans for the rest of the day, unless they involve chatting and/or napping. It&amp;rsquo;s the perfect antidote to the stresses of the season. &lt;/p&gt;
&lt;p style="text-align: center;"&gt;&lt;img alt="" src="/images/Recipes/granola.jpg" style="border: 0px;" /&gt;&lt;/p&gt;
&lt;p&gt; &lt;/p&gt;
&lt;p&gt; &lt;/p&gt;
&lt;p style="text-align: center;"&gt;&lt;a href="http://www.evoolution.ca/recipes/cranberry-coconut-granola"&gt;Cranberry Coconut Granola&lt;/a&gt;&lt;/p&gt;
&lt;p&gt; &lt;/p&gt;
&lt;p&gt; &lt;/p&gt;
&lt;p style="text-align: center;"&gt;&lt;img alt="" src="/images/Recipes/bran-muffins.jpg" style="border: 0px;" /&gt;&lt;/p&gt;
&lt;p style="text-align: center;"&gt;&lt;a href="http://www.evoolution.ca/recipes/pumpkin-bran-muffins"&gt;Pumpkin Bran Muffins&lt;/a&gt;&lt;/p&gt;
&lt;p style="text-align: center;"&gt;&lt;img alt="" src="/blog images/roseberry.jpg" style="border: 0px;" /&gt;&lt;/p&gt;
&lt;p&gt; &lt;/p&gt;
&lt;p&gt; &lt;/p&gt;
&lt;p style="text-align: center;"&gt;&lt;a href="http://www.evoolution.ca/recipes/blueberry-balsamic-jam-with-rosemary"&gt;Blueberry Balsamic Jam with Rosemary&lt;/a&gt;&lt;/p&gt;
&lt;p&gt; &lt;/p&gt;
&lt;p&gt; &lt;/p&gt;
&lt;p style="text-align: center;"&gt;&lt;img alt="" src="/images/Recipes/baked-eggs.jpg" style="border: 0px;" /&gt;&lt;/p&gt;
&lt;p style="text-align: center;"&gt;&lt;a href="http://www.evoolution.ca/recipes/baked-eggs-with-balsamic-braised-leeks"&gt;Baked Eggs with Balsamic-Braised Leeks&lt;/a&gt;&lt;/p&gt;
&lt;p style="text-align: center;"&gt;&lt;img alt="" src="/images/Recipes/cinnamonbuns2-lg.jpg" style="border: 0px;" /&gt;&lt;/p&gt;
&lt;p&gt; &lt;/p&gt;
&lt;p&gt; &lt;/p&gt;
&lt;p style="text-align: center;"&gt;&lt;a href="http://www.evoolution.ca/recipes/walnut-cinnamon-buns-with-lavender-frosting"&gt;Walnut Cinnamon Buns with Lavender Frosting&lt;/a&gt;&lt;/p&gt;
&lt;p&gt;
&lt;/p&gt;
&lt;div style="text-align: center;"&gt;&lt;br /&gt;
&lt;/div&gt;
</description><link>http://www.evoolution.ca/RSSRetrieve.aspx?ID=18298&amp;A=Link&amp;ObjectID=1163345&amp;ObjectType=56&amp;O=http%253a%252f%252fwww.evoolution.ca%252f_blog%252fEvoolution%252fpost%252fclear-your-plans%252f</link><guid isPermaLink="true">http://www.evoolution.ca/_blog/Evoolution/post/clear-your-plans/</guid><pubDate>Mon, 09 Dec 2013 18:09:00 GMT</pubDate></item><item><title>Holiday Gift Ideas</title><description>&lt;p&gt;It's only just December, but we're already in holiday mode! Here are some lovely gift ideas that are sure to please any recipient.&lt;/p&gt;
&lt;p&gt;&lt;img alt="" src="/blog images/books.jpg" style="border: 0px;" /&gt;&lt;/p&gt;
&lt;p&gt;Our selection of books is perfect for someone who wants to learn more about olive oil, from how it's made to how to use it (and don't forget the scandalous details of the olive oil industry)!&lt;/p&gt;
&lt;p&gt;&lt;img alt="" src="/blog images/cedar-boxes.jpg" style="border: 0px;" /&gt;&lt;/p&gt;
&lt;p&gt;Our cedar boxes are a fantastic, unique gift - choose from 3 sizes and fill with your choice of oil, vinegar and/or salts and spices. We have a variety of pre-filled boxes this year, if you need a little help or are in a hurry!&lt;/p&gt;
&lt;p&gt;&lt;img alt="" src="/blog images/olive-wood.jpg" style="border: 0px;" /&gt;&lt;/p&gt;
&lt;p&gt;Berard olive wood is always an elegant gift, and perfect for this season of entertaining.&amp;nbsp;&lt;/p&gt;
&lt;p&gt;&lt;img alt="" src="/blog images/salt-pepper-mills.jpg" style="border: 0px;" /&gt;&lt;/p&gt;
&lt;p&gt;Cole &amp;amp; Mason salt and pepper mills are a great gift for someone just starting out in the kitchen, or anyone looking to upgrade their tools!&lt;/p&gt;
&lt;p&gt;&lt;img alt="" src="/blog images/sample-packs.jpg" style="border: 0px;" /&gt;&lt;/p&gt;
&lt;p&gt;Our 6-bottle sample packs, with a choice of pre-made or custom (in-store), are already a perennial favourite.&lt;/p&gt;
&lt;p&gt;&lt;img alt="" src="/blog images/violet-choc.jpg" style="border: 0px;" /&gt;&lt;/p&gt;
&lt;p&gt;If you're looking to round out your gift, a Violet Chocolate Co. bar is always a good idea!&amp;nbsp;&lt;/p&gt;
&lt;p&gt;We'll also have a selection of baskets available, as well as salt packs and some gorgeous stainless steel products. See you soon! See our online selection of gift sets &lt;a href="http://www.evoolution.ca/gift_sets"&gt;here&lt;/a&gt;.&amp;nbsp;&lt;/p&gt;
</description><link>http://www.evoolution.ca/RSSRetrieve.aspx?ID=18298&amp;A=Link&amp;ObjectID=1153937&amp;ObjectType=56&amp;O=http%253a%252f%252fwww.evoolution.ca%252f_blog%252fEvoolution%252fpost%252fholiday-gift-ideas%252f</link><guid isPermaLink="true">http://www.evoolution.ca/_blog/Evoolution/post/holiday-gift-ideas/</guid><pubDate>Sun, 01 Dec 2013 05:00:00 GMT</pubDate></item><item><title>Iron Chef: Evoolution Edition - Round Four</title><description>&lt;div&gt;We had our latest recipe challenge on Monday night! If you've missed them, here are rounds &lt;a href="http://www.evoolution.ca/_blog/Evoolution/post/Iron_Chef/"&gt;one&lt;/a&gt;, &lt;a href="http://www.evoolution.ca/_blog/Evoolution/post/iron-chef-evoolution-edition---round-two/"&gt;two&lt;/a&gt; and &lt;a href="http://www.evoolution.ca/_blog/Evoolution/post/iron-chef-evoolution-edition---round-three/"&gt;three&lt;/a&gt;. We were a smaller group this time, thanks to the irksome snowfall, but a good time was still had all around.&lt;/div&gt;
&lt;div&gt;&lt;br /&gt;
&lt;/div&gt;
&lt;div&gt;
&lt;div style="text-align: center;"&gt;&lt;img alt="" src="/blog images/comp-shot.jpg" style="font-family: arial, helvetica, sans-serif; font-size: medium; font-style: normal; font-variant: normal; line-height: 24px;" /&gt;&lt;/div&gt;
&lt;br /&gt;
&lt;/div&gt;
&lt;div&gt;&lt;br /&gt;
&lt;/div&gt;
&lt;div&gt;For this challenge, everyone was given a specific dish to make, then allowed to choose which oil and vinegar they wanted to use; on the night of, we had a wonderful spread of soup, salad, shepherd's pie, chili and dessert.&amp;nbsp;&lt;/div&gt;
&lt;div&gt;&lt;br /&gt;
&lt;/div&gt;
&lt;div style="text-align: center;"&gt;&lt;img alt="" src="/blog images/vegetable-soup.jpg" style="font-family: arial, helvetica, sans-serif; line-height: 1.5;" /&gt;&lt;/div&gt;
&lt;div&gt;&lt;br /&gt;
&lt;/div&gt;
&lt;div&gt;Darren made a roasted vegetable soup with &lt;a href="http://www.evoolution.ca/oils_/organic-coratina"&gt;18-Year Traditional&lt;/a&gt; balsamic and &lt;a href="http://www.evoolution.ca/oils_/organic-coratina"&gt;Organic Coratina&lt;/a&gt; olive oil.&amp;nbsp;&lt;/div&gt;
&lt;div&gt;&lt;br /&gt;
&lt;/div&gt;
&lt;div&gt;
&lt;div style="text-align: center;"&gt;&lt;img alt="" src="/blog images/winter-salad.jpg" style="font-family: arial, helvetica, sans-serif; font-size: medium; font-style: normal; font-variant: normal; line-height: 24px; text-align: center;" /&gt;&lt;/div&gt;
&lt;div style="text-align: center;"&gt;&lt;br /&gt;
&lt;/div&gt;
&lt;div style="text-align: center;"&gt;Azkaa made a winter fruit salad with &lt;a href="http://www.evoolution.ca/vinegars_/cranberry-pear-white-balsamic-vinegar"&gt;Cranberry Pear&lt;/a&gt; balsamic and &lt;a href="http://www.evoolution.ca/oils_/persian-lime-olive-oil"&gt;Persian Lime&lt;/a&gt; oil.&lt;/div&gt;
&lt;/div&gt;
&lt;div&gt;&lt;br /&gt;
&lt;/div&gt;
&lt;div style="text-align: center;"&gt;&lt;img alt="" src="/blog images/shepherds-pie.jpg" style="border: 0px;" /&gt;&lt;/div&gt;
&lt;div style="text-align: center;"&gt;&lt;br /&gt;
&lt;/div&gt;
&lt;div style="text-align: center;"&gt;EJ made shepherd's pie with &lt;a href="http://www.evoolution.ca/oils_/white-truffle-oil-60"&gt;White Truffle&lt;/a&gt; mashed potatoes and &lt;a href="http://www.evoolution.ca/vinegars_/pomegranate-balsamic-vinegar"&gt;Pomegranate&lt;/a&gt; onion jam.&lt;/div&gt;
&lt;div style="text-align: center;"&gt;&lt;br /&gt;
&lt;/div&gt;
&lt;div style="text-align: center;"&gt;&lt;img alt="" src="/blog images/pulled-pork-chili.jpg" style="border: 0px;" /&gt;&lt;/div&gt;
&lt;div style="text-align: center;"&gt;&lt;br /&gt;
&lt;/div&gt;
&lt;div style="text-align: center;"&gt;Colin made pulled pork chili with &lt;a href="http://www.evoolution.ca/oils_/red-cayenne-chili"&gt;Red Cayenne Chili&lt;/a&gt; oil.&lt;/div&gt;
&lt;div style="text-align: center;"&gt;&lt;br /&gt;
&lt;/div&gt;
&lt;div style="text-align: center;"&gt;&lt;img alt="" src="/blog images/sticky-toffee-pudding.jpg" style="border: 0px;" /&gt;&lt;/div&gt;
&lt;div style="text-align: center;"&gt;&lt;br /&gt;
&lt;/div&gt;
&lt;div style="text-align: center;"&gt;Rachel P. made sticky toffee pudding with &lt;a href="http://www.evoolution.ca/oils_/blood-orange-olive-oil"&gt;Blood Orange&lt;/a&gt; oil and &lt;a href="http://www.evoolution.ca/vinegars_/cinnamon-pear-balsamic-vinegar"&gt;Cinnamon Pear&lt;/a&gt; balsamic.&lt;/div&gt;
&lt;div style="text-align: center;"&gt;&lt;br /&gt;
&lt;/div&gt;
&lt;div style="text-align: left;"&gt;As last round's winner, Teagan had the honour of judging. She chose EJ as the winner! He will judge the next round, which will take place sometime in the new year.&amp;nbsp;&lt;/div&gt;
&lt;div style="text-align: center;"&gt;&lt;br /&gt;
&lt;/div&gt;
</description><link>http://www.evoolution.ca/RSSRetrieve.aspx?ID=18298&amp;A=Link&amp;ObjectID=1154160&amp;ObjectType=56&amp;O=http%253a%252f%252fwww.evoolution.ca%252f_blog%252fEvoolution%252fpost%252firon-chef-evoolution-edition---round-four%252f</link><guid isPermaLink="true">http://www.evoolution.ca/_blog/Evoolution/post/iron-chef-evoolution-edition---round-four/</guid><pubDate>Wed, 20 Nov 2013 22:02:00 GMT</pubDate></item><item><title>Oil and vinegar - emulsified</title><description>&lt;p&gt;The backbone of any salad is the dressing; so how do you make yours perfect every time? Make sure to emulsify! An emulsion is a homogenous mixture of two or more liquids that normally cannot be blended. For our purposes, oil and vinegar are a good example.&amp;nbsp;&lt;/p&gt;
&lt;p&gt;
&lt;/p&gt;
&lt;div style="text-align: center;"&gt;&lt;img alt="" src="/blog images/olive-oil-balsamic.jpg" /&gt;&lt;/div&gt;
&lt;p style="text-align: center;"&gt;&lt;span style="font-size: 11px;"&gt;Image courtesy of &lt;a href="http://summertomato.com/the-bitter-truth-about-olive-oil/"&gt;Summer Tomato&lt;/a&gt;&lt;/span&gt;&lt;/p&gt;
&lt;p style="text-align: left;"&gt;To blend the two together, an emulsifying agent is necessary. Emulsifying agents such as mustard, egg yolk or honey contain both a water-soluble component and an oil-soluble component, lowering the surface tension between the two liquids and encouraging the suspension of one liquid in another.&amp;nbsp;&lt;/p&gt;
&lt;p style="text-align: center;"&gt;&lt;img alt="" src="/blog images/1005p228-mix-vinaigrette-l.jpg" style="border: 0px;" /&gt;&lt;/p&gt;
&lt;p style="text-align: center;"&gt;&lt;span style="font-size: 11px;"&gt;Image courtesy of &lt;a href="http://www.cookinglight.com/cooking-101/techniques/how-to-make-vinaigrette-recipes-00412000067320/"&gt;Cooking Light&lt;/a&gt;&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;If you&amp;rsquo;d like to dress your salad in advance, emulsifying is crucial &amp;ndash; without it, the dressing will separate, the oil clinging to the salad leaves and the vinegar sinking to the bottom. Overall, an emulsified vinaigrette will coat your salad better and keep it fresher when dressed; it will also keep longer on its own, in a jar in the fridge. &lt;/p&gt;
&lt;p style="text-align: center;"&gt;&lt;img alt="" src="/blog images/simones-shallot-vinaigrette-646.jpg" style="border: 0px;" /&gt;&lt;/p&gt;
&lt;p&gt; &lt;/p&gt;
&lt;p&gt; &lt;/p&gt;
&lt;p style="text-align: center;"&gt;&lt;span style="font-size: 11px;"&gt;Image courtesy of &lt;a href="http://www.bonappetit.com/recipe/simone-s-shallot-vinaigrette"&gt;Bon App&amp;eacute;tit&lt;/a&gt;&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;Here is a simple formula for vinaigrette (mustard is our favourite emulsifier, but an equal amount of egg yolk, honey or mayonnaise will also work).&amp;nbsp; Whisk 3 tbsp. of balsamic vinegar with 1 tbsp. of mustard and a big pinch of salt; whisking slowly, stream in &amp;frac12; cup of extra-virgin olive oil. Add fresh herbs and/or chopped shallots to taste. This can also be done in a blender. Enjoy!&lt;/p&gt;
</description><link>http://www.evoolution.ca/RSSRetrieve.aspx?ID=18298&amp;A=Link&amp;ObjectID=1149394&amp;ObjectType=56&amp;O=http%253a%252f%252fwww.evoolution.ca%252f_blog%252fEvoolution%252fpost%252foil-and-vinegar---emulsified%252f</link><guid isPermaLink="true">http://www.evoolution.ca/_blog/Evoolution/post/oil-and-vinegar---emulsified/</guid><pubDate>Fri, 08 Nov 2013 20:18:00 GMT</pubDate></item><item><title>Winter on the brain</title><description>&lt;p&gt;Well, with the temperature steadily dipping, we&amp;rsquo;ve got winter on the brain here at Evoolution! This excites us more than you might think. Some of our favourite things are abundant in winter &amp;ndash; beautiful citrus, pears and pomegranates, to name a few &amp;ndash; and in the coming weeks, we&amp;rsquo;ll be adding recipes that are perfect for this season of entertaining. &lt;/p&gt;
&lt;p style="text-align: center;"&gt;&lt;img alt="" src="/blog images/olive-oil-tart-crust.jpg" style="border: 0px;" /&gt;&lt;/p&gt;
&lt;p&gt; &lt;/p&gt;
&lt;p&gt; &lt;/p&gt;
&lt;p&gt;Today, we have a wonderfully flaky olive oil tart crust that couldn&amp;rsquo;t be simpler to make. This is the only crust you&amp;rsquo;ll ever need for any kind of savoury tart &amp;ndash; it is quicker and easier than its butter-filled counterparts, and crispy enough to stand up to a loose filling (no soggy bottom crust!).&lt;/p&gt;
&lt;p style="text-align: center;"&gt;&lt;img alt="" src="/blog images/balsamic-caramelized-onion-tart.jpg" style="border: 0px;" /&gt;&lt;/p&gt;
&lt;p&gt; To make an easy appetizer for a holiday party, simply roll out the dough and place it on a baking sheet; top with sharp mustard, &lt;a href="http://www.evoolution.ca/vinegars_/dark-chocolate-balsamic-vinegar"&gt;Dark Chocolate&lt;/a&gt; balsamic-caramelized onions and a nice, melty cheese, and bake until browned. Cut into small squares and serve with drinks and other nibbles. Recipe for the crust &lt;a href="http://www.evoolution.ca/recipes/savoury-olive-oil-tart-crust"&gt;here&lt;/a&gt;, and for the caramelized onion tart &lt;a href="http://www.evoolution.ca/recipes/balsamic-caramelized-onion-tart"&gt;here&lt;/a&gt;.&amp;nbsp;&lt;/p&gt;
</description><link>http://www.evoolution.ca/RSSRetrieve.aspx?ID=18298&amp;A=Link&amp;ObjectID=1145483&amp;ObjectType=56&amp;O=http%253a%252f%252fwww.evoolution.ca%252f_blog%252fEvoolution%252fpost%252fwinter-on-the-brain%252f</link><guid isPermaLink="true">http://www.evoolution.ca/_blog/Evoolution/post/winter-on-the-brain/</guid><pubDate>Fri, 01 Nov 2013 04:00:00 GMT</pubDate></item><item><title>The fresher the better</title><description>&lt;p&gt;We've got a &lt;a href="http://www.evoolution.ca/oils#pure_evoo"&gt;whole new crop of varietals&lt;/a&gt; in from the southern hemisphere, including our first oil from South Africa! Most of the oils were crushed at the beginning of the summer, making them some of the freshest olive oils around. The freshness of olive oil is crucial - the fresher the oil, the better it tastes and the better it is for you.&amp;nbsp;&lt;/p&gt;
&lt;p&gt;NPR recently did &lt;a href="http://www.npr.org/blogs/thesalt/2013/09/30/226844915/to-get-the-benefits-of-olive-oil-fresh-may-be-best"&gt;a piece on freshness in olive oil&lt;/a&gt;, citing Tom Mueller (author of &lt;em&gt;Extra Virginity&lt;/em&gt;) among others.&amp;nbsp;&lt;/p&gt;
&lt;p&gt;The Olive Oil Times has some tips on &lt;a href="http://www.oliveoiltimes.com/whats-cooking-with-olive-oil/keeping-olive-oil-fresh/878"&gt;how to keep olive oil fresh&lt;/a&gt;.&lt;/p&gt;
&lt;p&gt;Tom Mueller has a guide on &lt;a href="http://www.truthinoliveoil.com/great-oil/how-to-buy-great-olive-oil"&gt;how to buy great olive oil&lt;/a&gt;.&amp;nbsp;&lt;/p&gt;
</description><link>http://www.evoolution.ca/RSSRetrieve.aspx?ID=18298&amp;A=Link&amp;ObjectID=1142301&amp;ObjectType=56&amp;O=http%253a%252f%252fwww.evoolution.ca%252f_blog%252fEvoolution%252fpost%252fthe-fresher-the-better%252f</link><guid isPermaLink="true">http://www.evoolution.ca/_blog/Evoolution/post/the-fresher-the-better/</guid><pubDate>Fri, 25 Oct 2013 03:55:00 GMT</pubDate></item></channel></rss>